import type { ProductionModifier, ResourceAmounts } from './productionCalculator'

const ALL_RESOURCES: ResourceAmounts = { food: 1, wood: 1, gold: 1, stone: 1 }

function gathering(
  id: string,
  label: string,
  description: string,
  resourceMultiplier: Partial<ResourceAmounts>,
  options: Pick<ProductionModifier, 'defaultSelected' | 'foodSources' | 'age'> = {},
): ProductionModifier {
  return { id, label, description, kind: 'gathering', resourceMultiplier, ...options }
}

function dropOff(
  id: string,
  label: string,
  description: string,
  dropOffPercent: Partial<ResourceAmounts>,
  options: Pick<ProductionModifier, 'defaultSelected' | 'age'> = {},
): ProductionModifier {
  return { id, label, description, kind: 'dropOff', dropOffPercent, ...options }
}

function speed(
  id: string,
  label: string,
  description: string,
  multiplier: number,
  target: ProductionModifier['target'],
  options: Pick<ProductionModifier, 'defaultSelected' | 'age'> = {},
): ProductionModifier {
  return { id, label, description, kind: 'speed', multiplier, target, ...options }
}

function cost(
  id: string,
  label: string,
  description: string,
  multiplier: number,
  target: ProductionModifier['target'],
  options: Pick<ProductionModifier, 'defaultSelected' | 'age'> = {},
): ProductionModifier {
  return { id, label, description, kind: 'cost', multiplier, target, ...options }
}

function passive(
  id: string,
  label: string,
  description: string,
  passivePerMinute: Partial<ResourceAmounts>,
): ProductionModifier {
  return { id, label, description, kind: 'passive', passivePerMinute }
}

const CIV_MODIFIERS: Record<string, ProductionModifier[]> = {
  abbasid_dynasty: [],
  ayyubids: [],
  byzantines: [],
  chinese: [
    speed(
      'song-dynasty',
      'Song Dynasty',
      'Villager production is 33% faster while Song Dynasty is active.',
      1.33,
      { unitIds: ['villager'] },
    ),
    dropOff(
      'imperial-official',
      'Imperial Official supervision',
      'Adds 20% drop-off efficiency to the selected resource.',
      { food: 20, wood: 20, gold: 20, stone: 20 },
    ),
    gathering(
      'granary-farms',
      'Granary farms',
      'Granary aura increases farm gather rate by 12%.',
      { food: 1.12 },
      { foodSources: ['farm'] },
    ),
    speed('Chinese docks', 'Chinese docks', 'Chinese ships train 10% faster.', 1.1, {
      producedBy: ['dock'],
    }),
  ],
  delhi_sultanate: [
    gathering(
      'delhi-berry',
      'Delhi berry bonus',
      'Delhi berry gather rate is increased by 21.2%.',
      { food: 1.212 },
      { defaultSelected: true, foodSources: ['berry'] },
    ),
    passive('delhi-sacred-site', 'Sacred site gold', 'Gold generated by sacred sites.', {
      gold: 25,
    }),
  ],
  english: [
    gathering(
      'english-farms-dark',
      'English farms · Dark',
      'English farms gather 17% faster in the Dark Age.',
      { food: 1.17 },
      { defaultSelected: true, foodSources: ['farm'], age: 1 },
    ),
    gathering(
      'english-farms-feudal',
      'English farms · Feudal',
      'English farms gather 20% faster in the Feudal Age.',
      { food: 1.2 },
      { defaultSelected: true, foodSources: ['farm'], age: 2 },
    ),
    gathering(
      'english-farms-castle',
      'English farms · Castle',
      'English farms gather 24% faster in the Castle Age.',
      { food: 1.24 },
      { defaultSelected: true, foodSources: ['farm'], age: 3 },
    ),
    gathering(
      'english-farms-imperial',
      'English farms · Imperial',
      'English farms gather 24% faster in the Imperial Age.',
      { food: 1.24 },
      { defaultSelected: true, foodSources: ['farm'], age: 4 },
    ),
    cost('english-dock', 'English dock discount', 'English ships cost 10% less.', 0.9, {
      producedBy: ['dock'],
    }),
    speed(
      'white-tower',
      'The White Tower',
      'Units produced by The White Tower train 75% faster.',
      1.75,
      { producedBy: ['the-white-tower'] },
    ),
    speed(
      'english-man-at-arms',
      'English men-at-arms',
      'English men-at-arms train 40% faster.',
      1.4,
      { unitIds: ['man-at-arms'] },
    ),
  ],
  french: [
    speed(
      'school-of-cavalry',
      'School of Cavalry',
      'Cavalry produced by the School of Cavalry trains 20% faster.',
      1.2,
      { classes: ['cavalry'] },
    ),
    cost(
      'royal-institute-stable',
      'French stable discount',
      'Units from the French stable cost 20% less.',
      0.8,
      { producedBy: ['stable'] },
    ),
    cost(
      'french-archery-range',
      'French archery range discount',
      'Units from the French archery range cost 5% less.',
      0.95,
      { producedBy: ['archery-range'] },
    ),
  ],
  golden_horde: [
    gathering(
      'golden-horde-stockyard',
      'Rotation Grazing',
      'Stockyard food gather rate is increased by 9.7%.',
      { food: 1.097 },
      { foodSources: ['stockyard'] },
    ),
    gathering(
      'golden-horde-overgrazing',
      'Over Grazing',
      'Stockyard food gather rate is increased by 9.5%.',
      { food: 1.095 },
      { foodSources: ['stockyard'] },
    ),
    speed(
      'golden-horde-production-edict',
      'Production Speed Edict',
      'Military production speed is increased by 15%.',
      1.15,
      { classes: ['infantry', 'cavalry', 'ranged', 'siege', 'elephant', 'camel'] },
    ),
    speed(
      'golden-horde-increased-supplies',
      'Increased Supplies',
      'Military production speed is increased by 50%.',
      1.5,
      { classes: ['infantry', 'cavalry', 'ranged', 'siege', 'elephant', 'camel'] },
    ),
    passive(
      'golden-horde-stockyard-edict',
      'Stockyard Edict',
      'Stockyard Edict passive gold income.',
      { gold: 40 },
    ),
  ],
  house_of_lancaster: [
    gathering(
      'lancaster-sheep',
      'House of Lancaster sheep bonus',
      'Sheep gather rate is increased by 20%.',
      { food: 1.2 },
      { defaultSelected: true, foodSources: ['sheep'] },
    ),
  ],
  holy_roman_empire: [],
  japanese: [],
  jeanne_darc: [],
  jin_dynasty: [],
  knights_templar: [],
  malians: [],
  macedonian_dynasty: [
    gathering(
      'grand-winery',
      'Grand Winery',
      'Food gather rate is increased by 23% while Grand Winery is active.',
      { food: 1.23 },
      { defaultSelected: true },
    ),
  ],
  mongols: [
    gathering(
      'improved-double-broadaxe',
      'Improved Double Broadaxe',
      'Improved technology increases wood gather rate by 16%.',
      { wood: 1.16 },
    ),
    gathering(
      'improved-horticulture',
      'Improved Horticulture',
      'Improved technology increases food gather rate by 16%.',
      { food: 1.16 },
    ),
    gathering(
      'improved-specialized-pick',
      'Improved Specialized Pick',
      'Improved technology increases gold and stone gather rate by 16%.',
      { gold: 1.16, stone: 1.16 },
    ),
    dropOff('steppe-redoubt', 'Steppe Redoubt', 'Gold drop-off efficiency is increased by 50%.', {
      gold: 50,
    }),
  ],
  order_of_the_dragon: [],
  ottomans: [
    speed(
      'ottoman-blacksmith-feudal',
      'Ottoman blacksmith · Feudal',
      'Military production speed bonus from the blacksmith.',
      1.2,
      { classes: ['infantry', 'cavalry', 'ranged', 'siege', 'elephant', 'camel'] },
      { age: 2 },
    ),
    speed(
      'ottoman-blacksmith-castle',
      'Ottoman blacksmith · Castle',
      'Military production speed bonus from the blacksmith.',
      1.3,
      { classes: ['infantry', 'cavalry', 'ranged', 'siege', 'elephant', 'camel'] },
      { age: 3 },
    ),
    speed(
      'ottoman-blacksmith-imperial',
      'Ottoman blacksmith · Imperial',
      'Military production speed bonus from the blacksmith.',
      1.4,
      { classes: ['infantry', 'cavalry', 'ranged', 'siege', 'elephant', 'camel'] },
      { age: 4 },
    ),
    speed(
      'ottoman-observatory',
      'Istanbul Observatory',
      'Units produced by the Istanbul Observatory train 90% faster.',
      1.9,
      { producedBy: ['military-school'] },
    ),
  ],
  rus: [
    gathering(
      'rus-bounty-tier-1',
      'Rus bounty · Tier I',
      'Bounty increases food gather rate by 7%.',
      { food: 1.07 },
      { defaultSelected: true },
    ),
    gathering(
      'rus-bounty-tier-2',
      'Rus bounty · Tier II',
      'Bounty increases food gather rate by 11%.',
      { food: 1.11 },
    ),
    gathering(
      'rus-bounty-tier-3',
      'Rus bounty · Tier III',
      'Bounty increases food gather rate by 15%.',
      { food: 1.15 },
    ),
    dropOff('wooden-fortress', 'Wooden Fortress', 'Wood drop-off efficiency is increased by 20%.', {
      wood: 20,
    }),
  ],
  sengoku_daimyo: [
    speed(
      'daimyo-estate',
      'Daimyo Estate',
      'Infantry and cavalry produced by a Daimyo Estate train 20% faster.',
      1.2,
      { classes: ['infantry', 'cavalry'] },
    ),
  ],
  tughlaq_dynasty: [
    gathering(
      'tughlaq-eco-food',
      'Tughlaq food economy',
      'Tughlaq eco bonus increases food gather rate by 3.85%.',
      { food: 1.0385 },
      { defaultSelected: true },
    ),
    gathering(
      'tughlaq-eco-wood',
      'Tughlaq wood economy',
      'Tughlaq eco bonus increases wood gather rate by 3.2%.',
      { wood: 1.032 },
      { defaultSelected: true },
    ),
    gathering(
      'tughlaq-eco-gold-stone',
      'Tughlaq gold and stone economy',
      'Tughlaq eco bonus increases gold and stone gather rate by 3.85%.',
      { gold: 1.0385, stone: 1.0385 },
      { defaultSelected: true },
    ),
    dropOff(
      'tughlaq-dropoff',
      'Tughlaq resource drop-off',
      'Resource drop-off efficiency is increased by 5%.',
      { food: 5, wood: 5, gold: 5, stone: 5 },
      { defaultSelected: true },
    ),
  ],
  zhu_xis_legacy: [],
}

/** Current calculator-style optional civ modifiers, kept as local data so the math stays testable. */
export function productionModifiersForCiv(civ: string): ProductionModifier[] {
  return (CIV_MODIFIERS[civ] ?? []).map((modifier) => ({
    ...modifier,
    resourceMultiplier: modifier.resourceMultiplier
      ? { ...ALL_RESOURCES, ...modifier.resourceMultiplier }
      : undefined,
    dropOffPercent: modifier.dropOffPercent ? { ...modifier.dropOffPercent } : undefined,
    passivePerMinute: modifier.passivePerMinute ? { ...modifier.passivePerMinute } : undefined,
  }))
}
