import type { BuildOrderVideoEvidence } from '@domain/videoEvidence'

/** Generated by scripts/harvest_aoe4_videos.py; do not edit by hand. */
export const VIDEO_EVIDENCE_BY_CIV: Record<string, BuildOrderVideoEvidence> = {
  "english": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 4,
    "requestedSampleSize": 100,
    "coverageNote": "4 matching videos found; requested 100",
    "commonActions": [
      "Boom"
    ],
    "commonResources": [],
    "commonTopics": [
      "Opening military",
      "Age-up",
      "Counterplay",
      "Economy"
    ],
    "commonOpponents": [
      "Abbasid Dynasty",
      "Ayyubids",
      "Byzantines",
      "Chinese",
      "Delhi Sultanate",
      "French",
      "Japanese",
      "Holy Roman Empire"
    ],
    "commonMilitaryMentions": [
      "Knight",
      "Spearman"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "4:39",
        "timeSec": 279,
        "mentions": 1
      },
      {
        "label": "13:02",
        "timeSec": 782,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "kS9lnHO9h-w",
        "title": "The Algorithm Found Another RIDICULOUS Game",
        "url": "https://www.youtube.com/watch?v=kS9lnHO9h-w",
        "channel": "Aussie_Drongo",
        "publishedAt": "2026-08-08T14:00:32+00:00",
        "viewCount": 3056,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Boom",
          "actions": [
            "Boom"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Byzantines",
            "Chinese",
            "Delhi Sultanate",
            "French"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "4:39",
              "timeSec": 279,
              "mentions": 1
            },
            {
              "label": "13:02",
              "timeSec": 782,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "whV7qTyBEeI",
        "title": "AoE4 Ranked Multiplayer - Japanese vs English | Gorge 1v1 (2026/07/19)",
        "url": "https://www.youtube.com/watch?v=whV7qTyBEeI",
        "channel": "Arnob Paul",
        "publishedAt": "2026-07-26T15:00:18+00:00",
        "viewCount": 54,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Counterplay"
          ],
          "opponentCivs": [
            "Japanese"
          ],
          "militaryMentions": [
            "Spearman"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "FSqzyFg17Ug",
        "title": "How to Play English Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=FSqzyFg17Ug",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-12T12:00:07+00:00",
        "viewCount": 18324,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Opening military",
            "Counterplay"
          ],
          "opponentCivs": [
            "Holy Roman Empire",
            "Knights Templar",
            "Mongols",
            "Zhu Xi's Legacy"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "H1zXzBNQ9pM",
        "title": "Mastering the AOE4 English Rush Strategy to Reach Conqueror Rank Faster",
        "url": "https://www.youtube.com/watch?v=H1zXzBNQ9pM",
        "channel": "GROOT IS LIVE",
        "publishedAt": "2026-07-12T03:01:38+00:00",
        "viewCount": 32,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "macedoniandynasty": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Fast Castle",
      "Feudal aggression",
      "All-in"
    ],
    "commonResources": [],
    "commonTopics": [
      "Age-up",
      "Economy",
      "Counterplay"
    ],
    "commonOpponents": [
      "Ayyubids",
      "Holy Roman Empire",
      "Rus"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:11",
        "timeSec": 71,
        "mentions": 1
      },
      {
        "label": "29:24",
        "timeSec": 1764,
        "mentions": 1
      },
      {
        "label": "54:37",
        "timeSec": 3277,
        "mentions": 1
      },
      {
        "label": "95:00",
        "timeSec": 5700,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "d_FEca71_Xo",
        "title": "How to Play HRE Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=d_FEca71_Xo",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-08-06T11:30:33+00:00",
        "viewCount": 8583,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Fast Castle",
            "Feudal aggression",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Ayyubids",
            "Holy Roman Empire",
            "Rus"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:11",
              "timeSec": 71,
              "mentions": 1
            },
            {
              "label": "29:24",
              "timeSec": 1764,
              "mentions": 1
            },
            {
              "label": "54:37",
              "timeSec": 3277,
              "mentions": 1
            },
            {
              "label": "95:00",
              "timeSec": 5700,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      }
    ]
  },
  "ayyubids": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 6,
    "requestedSampleSize": 100,
    "coverageNote": "6 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Fast Castle",
      "Feudal aggression",
      "All-in"
    ],
    "commonResources": [
      "stone"
    ],
    "commonTopics": [
      "Counterplay",
      "Age-up",
      "Economy",
      "Opening military",
      "Map control"
    ],
    "commonOpponents": [
      "Holy Roman Empire",
      "Macedonian Dynasty",
      "Rus",
      "Japanese"
    ],
    "commonMilitaryMentions": [
      "Spearman"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:11",
        "timeSec": 71,
        "mentions": 1
      },
      {
        "label": "29:24",
        "timeSec": 1764,
        "mentions": 1
      },
      {
        "label": "54:37",
        "timeSec": 3277,
        "mentions": 1
      },
      {
        "label": "95:00",
        "timeSec": 5700,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "d_FEca71_Xo",
        "title": "How to Play HRE Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=d_FEca71_Xo",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-08-06T11:30:33+00:00",
        "viewCount": 8623,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Fast Castle",
            "Feudal aggression",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Holy Roman Empire",
            "Macedonian Dynasty",
            "Rus"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:11",
              "timeSec": 71,
              "mentions": 1
            },
            {
              "label": "29:24",
              "timeSec": 1764,
              "mentions": 1
            },
            {
              "label": "54:37",
              "timeSec": 3277,
              "mentions": 1
            },
            {
              "label": "95:00",
              "timeSec": 5700,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "4QoOqaQsl5s",
        "title": "BO Ayyubids AGRESSIF & SIMPLE ! SAISON 13 - Build Order Ayyubids AOE 4 - Age Of Empires 4",
        "url": "https://www.youtube.com/watch?v=4QoOqaQsl5s",
        "channel": "Jeando Tutos ",
        "publishedAt": "2026-08-04T12:00:06+00:00",
        "viewCount": 222,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "_3Cg1RsHWH8",
        "title": "Practicing the new build | Ayyubids Ridiculous AI | Dry Arabia | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=_3Cg1RsHWH8",
        "channel": "The Ever Padawan Archives",
        "publishedAt": "2026-08-02T22:00:31+00:00",
        "viewCount": 2,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "aRvS6nnLtU4",
        "title": "CE BO Ayyubids est EXCEPTIONNEL ! SAISON 13 - Build Order Ayyubids AOE 4 - Age Of Empires 4",
        "url": "https://www.youtube.com/watch?v=aRvS6nnLtU4",
        "channel": "Jeando Tutos ",
        "publishedAt": "2026-07-26T12:00:06+00:00",
        "viewCount": 639,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "Yr_u-odNztI",
        "title": "BO INCROYABLE Ayyubids ! SAISON 13 - Build Order Ayyubids AOE 4 - Age Of Empires 4",
        "url": "https://www.youtube.com/watch?v=Yr_u-odNztI",
        "channel": "Jeando Tutos ",
        "publishedAt": "2026-07-23T15:19:08+00:00",
        "viewCount": 556,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "GgPa3nWpq7U",
        "title": "AoE4 Ranked Multiplayer - Japanese vs Ayyubids | Gorge 1v1 (2026/07/09)",
        "url": "https://www.youtube.com/watch?v=GgPa3nWpq7U",
        "channel": "Arnob Paul",
        "publishedAt": "2026-07-18T15:00:10+00:00",
        "viewCount": 39,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "stone"
          ],
          "topics": [
            "Opening military",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Japanese"
          ],
          "militaryMentions": [
            "Spearman"
          ],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "knightstemplar": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 3,
    "requestedSampleSize": 100,
    "coverageNote": "3 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Boom",
      "All-in"
    ],
    "commonResources": [
      "gold"
    ],
    "commonTopics": [
      "Economy",
      "Counterplay",
      "Map control",
      "Opening military",
      "Technology"
    ],
    "commonOpponents": [
      "English",
      "Rus"
    ],
    "commonMilitaryMentions": [
      "Knight",
      "Siege"
    ],
    "timingSignals": [],
    "sources": [
      {
        "id": "E5kWEIbiZwo",
        "title": "Men At Arms For All And All For Men At Arms 1v1 (Ranked English vs Knights Templar)",
        "url": "https://www.youtube.com/watch?v=E5kWEIbiZwo",
        "channel": "Rocco's Gaming Journey",
        "publishedAt": "2026-08-01T16:00:06+00:00",
        "viewCount": 10,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "English"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "560HYfVvVOc",
        "title": "The Rus Gold Economy is IMPRESSIVE - AoE4",
        "url": "https://www.youtube.com/watch?v=560HYfVvVOc",
        "channel": "Cryptic RTS",
        "publishedAt": "2026-07-20T22:56:25+00:00",
        "viewCount": 1022,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "gold"
          ],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [
            "Rus"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "Fmv3s8EDEwE",
        "title": "How to Counter 2 TC Knights templar as Ottoman",
        "url": "https://www.youtube.com/watch?v=Fmv3s8EDEwE",
        "channel": "hello Tomi",
        "publishedAt": "2026-07-14T18:17:02+00:00",
        "viewCount": 62,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Boom",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Opening military",
            "Economy",
            "Technology",
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [
            "Knight",
            "Siege"
          ],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "goldenhorde": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 9,
    "requestedSampleSize": 100,
    "coverageNote": "9 matching videos found; requested 100",
    "commonActions": [
      "Boom",
      "Defensive"
    ],
    "commonResources": [
      "stone"
    ],
    "commonTopics": [
      "Economy",
      "Counterplay",
      "Opening military",
      "Map control",
      "Age-up"
    ],
    "commonOpponents": [
      "Delhi Sultanate",
      "Abbasid Dynasty",
      "Ayyubids",
      "Byzantines",
      "Chinese",
      "English",
      "Order of the Dragon",
      "Jin Dynasty"
    ],
    "commonMilitaryMentions": [
      "Knight"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "4:39",
        "timeSec": 279,
        "mentions": 1
      },
      {
        "label": "13:02",
        "timeSec": 782,
        "mentions": 1
      },
      {
        "label": "25:16",
        "timeSec": 1516,
        "mentions": 1
      },
      {
        "label": "47:47",
        "timeSec": 2867,
        "mentions": 1
      },
      {
        "label": "89:15",
        "timeSec": 5355,
        "mentions": 1
      },
      {
        "label": "116:48",
        "timeSec": 7008,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "kS9lnHO9h-w",
        "title": "The Algorithm Found Another RIDICULOUS Game",
        "url": "https://www.youtube.com/watch?v=kS9lnHO9h-w",
        "channel": "Aussie_Drongo",
        "publishedAt": "2026-08-08T14:00:32+00:00",
        "viewCount": 3056,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Boom",
          "actions": [
            "Boom"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Byzantines",
            "Chinese",
            "Delhi Sultanate",
            "English"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "4:39",
              "timeSec": 279,
              "mentions": 1
            },
            {
              "label": "13:02",
              "timeSec": 782,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "I1jDoMWx6f8",
        "title": "What a Quicky. (Diamond I) AoE IV : Ranked 1vs1 Golden Horde vs Macedonians",
        "url": "https://www.youtube.com/watch?v=I1jDoMWx6f8",
        "channel": "Xeriuz",
        "publishedAt": "2026-08-08T07:38:44+00:00",
        "viewCount": 8,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "2OYnHJTdi68",
        "title": "AGE OF EMPIRES 4 GOLDEN HORDE RANKED LOBBIES",
        "url": "https://www.youtube.com/watch?v=2OYnHJTdi68",
        "channel": "Topchi Pasha 666",
        "publishedAt": "2026-08-03T21:55:05+00:00",
        "viewCount": 28,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "noeLG_yfEdY",
        "title": "And My TC Still Stands. (Platinum II) AoE IV : Ranked 1vs1 OotD vs Golden Horde",
        "url": "https://www.youtube.com/watch?v=noeLG_yfEdY",
        "channel": "Xeriuz",
        "publishedAt": "2026-07-26T20:55:18+00:00",
        "viewCount": 30,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Order of the Dragon"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "F7V0Cnb4QZQ",
        "title": "The Craziest Strategy I Have Seen So Far. (Platinum II) AoE IV : Ranked 1vs1 Golden Horde vs Lancast",
        "url": "https://www.youtube.com/watch?v=F7V0Cnb4QZQ",
        "channel": "Xeriuz",
        "publishedAt": "2026-07-24T20:21:04+00:00",
        "viewCount": 99,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "SjFrYpES0jw",
        "title": "Golden Horde is impressive in Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=SjFrYpES0jw",
        "channel": "GiveUAnxiety",
        "publishedAt": "2026-07-23T11:34:09+00:00",
        "viewCount": 513,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "twutEhcJzq4",
        "title": "Golden Horde: What I Learned (And You Should Know)",
        "url": "https://www.youtube.com/watch?v=twutEhcJzq4",
        "channel": "TEAMTRIANGLE",
        "publishedAt": "2026-07-22T15:23:52+00:00",
        "viewCount": 466,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "stone"
          ],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "dbqW6d5PsX4",
        "title": "How to Play Mongols Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=dbqW6d5PsX4",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-19T11:40:08+00:00",
        "viewCount": 9710,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Defensive",
          "actions": [
            "Defensive"
          ],
          "resources": [],
          "topics": [
            "Opening military",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Delhi Sultanate",
            "Jin Dynasty",
            "Macedonian Dynasty",
            "Mongols"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "25:16",
              "timeSec": 1516,
              "mentions": 1
            },
            {
              "label": "47:47",
              "timeSec": 2867,
              "mentions": 1
            },
            {
              "label": "89:15",
              "timeSec": 5355,
              "mentions": 1
            },
            {
              "label": "116:48",
              "timeSec": 7008,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "68z2MJFYeEI",
        "title": "Golden Horn Tower Can´t Stop Me! (Platinum I) AoE IV : Ranked 1vs1 Golden Horde vs Macedonians",
        "url": "https://www.youtube.com/watch?v=68z2MJFYeEI",
        "channel": "Xeriuz",
        "publishedAt": "2026-07-14T14:00:03+00:00",
        "viewCount": 69,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "orderofthedragon": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 4,
    "requestedSampleSize": 100,
    "coverageNote": "4 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Defensive"
    ],
    "commonResources": [
      "gold",
      "food",
      "wood",
      "stone"
    ],
    "commonTopics": [
      "Age-up",
      "Counterplay",
      "Economy",
      "Map control"
    ],
    "commonOpponents": [
      "Rus",
      "French",
      "Mongols"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "f-BzxMnvN-Y",
        "title": "Por este BUILD ORDER volví a tener fe en La ORDEN DEL DRAGÓN | Guía AOE4",
        "url": "https://www.youtube.com/watch?v=f-BzxMnvN-Y",
        "channel": "VortiX",
        "publishedAt": "2026-08-04T18:00:03+00:00",
        "viewCount": 3312,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [
            "Rus"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "QwM9KLK9oGU",
        "title": "This Is the Safest Strategy in AoE4 — And It Actually Wins",
        "url": "https://www.youtube.com/watch?v=QwM9KLK9oGU",
        "channel": "ForTheMax",
        "publishedAt": "2026-07-28T14:31:49+00:00",
        "viewCount": 204,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Defensive"
          ],
          "resources": [
            "gold",
            "food",
            "wood",
            "stone"
          ],
          "topics": [
            "Age-up",
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "French"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "-kYstQVFEMQ",
        "title": "Guía para jugar TEMPLARIOS en 2026 | TUTORIAL AOE4 📚",
        "url": "https://www.youtube.com/watch?v=-kYstQVFEMQ",
        "channel": "VortiX",
        "publishedAt": "2026-07-17T17:00:26+00:00",
        "viewCount": 3983,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "nfNEctEHcKY",
        "title": "This Strategy Should Be Actually Illegal. AoE4. OOTD vs Mongols",
        "url": "https://www.youtube.com/watch?v=nfNEctEHcKY",
        "channel": "ForTheMax",
        "publishedAt": "2026-07-14T16:00:27+00:00",
        "viewCount": 288,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "gold"
          ],
          "topics": [
            "Age-up",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Mongols"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "zhuxislegacy": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 3,
    "requestedSampleSize": 100,
    "coverageNote": "3 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [],
    "commonTopics": [],
    "commonOpponents": [],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "5hEzJSWbE9I",
        "title": "Trying out a new build | Zhu Xi's Legacy Intermediate AI | Dry Arabia | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=5hEzJSWbE9I",
        "channel": "The Ever Padawan Archives",
        "publishedAt": "2026-07-29T12:00:36+00:00",
        "viewCount": 8,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "XvEl-oF-C5w",
        "title": "Practice against AI | Zhu Xi's Legacy Ridiculous AI | Carmel | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=XvEl-oF-C5w",
        "channel": "The Ever Padawan Archives",
        "publishedAt": "2026-07-21T12:00:29+00:00",
        "viewCount": 27,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "q4l1JEKYdSQ",
        "title": "Practice against AI | Zhu Xi's Legacy Outrageous AI | Carmel | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=q4l1JEKYdSQ",
        "channel": "The Ever Padawan Archives",
        "publishedAt": "2026-07-17T12:00:23+00:00",
        "viewCount": 110,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "japanese": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [
      "2TC"
    ],
    "commonResources": [],
    "commonTopics": [
      "Economy"
    ],
    "commonOpponents": [],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "TSrMgLt1ZTI",
        "title": "Going For Aussie Drongo Japanese 2 TC Build on Ladder",
        "url": "https://www.youtube.com/watch?v=TSrMgLt1ZTI",
        "channel": "BeastyqtGaming",
        "publishedAt": "2026-07-25T21:30:22+00:00",
        "viewCount": 4707,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "jindynasty": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [],
    "commonTopics": [
      "Counterplay"
    ],
    "commonOpponents": [
      "Ottomans"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "6iVfTOmxuKc",
        "title": "This May be the most Annoying Jin Dynasty Build",
        "url": "https://www.youtube.com/watch?v=6iVfTOmxuKc",
        "channel": "Mao Mao",
        "publishedAt": "2026-08-03T16:00:39+00:00",
        "viewCount": 1230,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [
            "Ottomans"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "abbasiddynasty": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 3,
    "requestedSampleSize": 100,
    "coverageNote": "3 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "All-in"
    ],
    "commonResources": [
      "gold"
    ],
    "commonTopics": [
      "Economy",
      "Opening military",
      "Counterplay"
    ],
    "commonOpponents": [
      "Byzantines",
      "English",
      "Tughlaq Dynasty"
    ],
    "commonMilitaryMentions": [
      "Siege"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:48",
        "timeSec": 108,
        "mentions": 1
      },
      {
        "label": "22:45",
        "timeSec": 1365,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "6iArDt0xmI4",
        "title": "Climbing to PLATINUM with ABBASID DYNASTY in AoE4 Ranked! 🐫 (Gold to Plat)",
        "url": "https://www.youtube.com/watch?v=6iArDt0xmI4",
        "channel": "NightShift Gaming",
        "publishedAt": "2026-08-01T21:33:55+00:00",
        "viewCount": 42,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [
            "gold"
          ],
          "topics": [
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [],
          "militaryMentions": [
            "Siege"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "HTX6g8AEsqI",
        "title": "Learning from one of the Best Abbasid Players in AOE4",
        "url": "https://www.youtube.com/watch?v=HTX6g8AEsqI",
        "channel": "Mao Mao Learns Gaming",
        "publishedAt": "2026-07-28T13:45:45+00:00",
        "viewCount": 607,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "UOHPB6LxNq4",
        "title": "How to Play Abbasid Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=UOHPB6LxNq4",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-26T11:30:15+00:00",
        "viewCount": 9317,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Byzantines",
            "English",
            "Tughlaq Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:48",
              "timeSec": 108,
              "mentions": 1
            },
            {
              "label": "22:45",
              "timeSec": 1365,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      }
    ]
  },
  "french": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 0,
    "requestedSampleSize": 100,
    "coverageNote": "0 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [],
    "timingSignals": [],
    "sources": [],
    "commonTopics": [],
    "commonOpponents": [],
    "commonMilitaryMentions": []
  },
  "houseoflancaster": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 4,
    "requestedSampleSize": 100,
    "coverageNote": "4 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Feudal aggression",
      "All-in",
      "Trade"
    ],
    "commonResources": [],
    "commonTopics": [
      "Economy",
      "Age-up",
      "Counterplay"
    ],
    "commonOpponents": [
      "English",
      "French",
      "Golden Horde",
      "Tughlaq Dynasty"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:35",
        "timeSec": 95,
        "mentions": 1
      },
      {
        "label": "77:55",
        "timeSec": 4675,
        "mentions": 1
      },
      {
        "label": "102:57",
        "timeSec": 6177,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "yMMGEzXByag",
        "title": "Haus Lancaster AoE4 Guide 2026 | Build Order und Erklärung der Spielweise",
        "url": "https://www.youtube.com/watch?v=yMMGEzXByag",
        "channel": "LaSh",
        "publishedAt": "2026-08-08T10:00:30+00:00",
        "viewCount": 724,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "Xkn4xxJg8GY",
        "title": "The Lancaster Feudal All In Is Still Very Strong | Think Like A Pro | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=Xkn4xxJg8GY",
        "channel": "Valdy",
        "publishedAt": "2026-07-24T16:00:39+00:00",
        "viewCount": 3602,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Feudal aggression",
          "actions": [
            "Feudal aggression",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Age-up"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "MD-9MfZWXOk",
        "title": "أقوى Build Order للانكستر! خطة 2TC تسيطر بيها على الماتش | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=MD-9MfZWXOk",
        "channel": "Lords OF The Games | أسياد الالعاب",
        "publishedAt": "2026-07-17T17:25:07+00:00",
        "viewCount": 298,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "b4BfCqoyQuE",
        "title": "How to Play French Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=b4BfCqoyQuE",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-15T13:37:45+00:00",
        "viewCount": 17028,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Trade"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "English",
            "French",
            "Golden Horde",
            "Tughlaq Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:35",
              "timeSec": 95,
              "mentions": 1
            },
            {
              "label": "77:55",
              "timeSec": 4675,
              "mentions": 1
            },
            {
              "label": "102:57",
              "timeSec": 6177,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      }
    ]
  },
  "byzantines": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 5,
    "requestedSampleSize": 100,
    "coverageNote": "5 matching videos found; requested 100",
    "commonActions": [
      "Boom",
      "2TC",
      "All-in"
    ],
    "commonResources": [],
    "commonTopics": [
      "Counterplay",
      "Economy",
      "Age-up",
      "Opening military"
    ],
    "commonOpponents": [
      "Abbasid Dynasty",
      "Delhi Sultanate",
      "English",
      "Ayyubids",
      "Chinese",
      "French",
      "Tughlaq Dynasty"
    ],
    "commonMilitaryMentions": [
      "Knight"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 2
      },
      {
        "label": "4:39",
        "timeSec": 279,
        "mentions": 1
      },
      {
        "label": "13:02",
        "timeSec": 782,
        "mentions": 1
      },
      {
        "label": "1:48",
        "timeSec": 108,
        "mentions": 1
      },
      {
        "label": "22:45",
        "timeSec": 1365,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "kS9lnHO9h-w",
        "title": "The Algorithm Found Another RIDICULOUS Game",
        "url": "https://www.youtube.com/watch?v=kS9lnHO9h-w",
        "channel": "Aussie_Drongo",
        "publishedAt": "2026-08-08T14:00:32+00:00",
        "viewCount": 2984,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Boom",
          "actions": [
            "Boom"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Chinese",
            "Delhi Sultanate",
            "English",
            "French"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "4:39",
              "timeSec": 279,
              "mentions": 1
            },
            {
              "label": "13:02",
              "timeSec": 782,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "FKN2RyQ5YEA",
        "title": "The Byzantines are AT THE GATES - Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=FKN2RyQ5YEA",
        "channel": "Cryptic RTS",
        "publishedAt": "2026-07-26T17:56:02+00:00",
        "viewCount": 599,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "UOHPB6LxNq4",
        "title": "How to Play Abbasid Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=UOHPB6LxNq4",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-26T11:30:15+00:00",
        "viewCount": 9317,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "English",
            "Tughlaq Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:48",
              "timeSec": 108,
              "mentions": 1
            },
            {
              "label": "22:45",
              "timeSec": 1365,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "fzcprhgCkvM",
        "title": "170W AoE4 Byz ranked vs. Tuqluq Fort Rush",
        "url": "https://www.youtube.com/watch?v=fzcprhgCkvM",
        "channel": "TRAJAN AoE4",
        "publishedAt": "2026-07-25T23:01:30+00:00",
        "viewCount": 34,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "VldYl0zk8iQ",
        "title": "This Byzantine Hippodrome Build is crazy Strong",
        "url": "https://www.youtube.com/watch?v=VldYl0zk8iQ",
        "channel": "Mao Mao",
        "publishedAt": "2026-07-12T19:10:04+00:00",
        "viewCount": 1310,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Counterplay"
          ],
          "opponentCivs": [
            "Delhi Sultanate"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "chinese": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [
      "Feudal aggression",
      "All-in"
    ],
    "commonResources": [],
    "commonTopics": [
      "Age-up",
      "Opening military",
      "Economy"
    ],
    "commonOpponents": [
      "Abbasid Dynasty",
      "Ayyubids",
      "Byzantines",
      "Delhi Sultanate",
      "English",
      "French"
    ],
    "commonMilitaryMentions": [
      "Knight"
    ],
    "timingSignals": [
      {
        "label": "5:41",
        "timeSec": 341,
        "mentions": 1
      },
      {
        "label": "8:29",
        "timeSec": 509,
        "mentions": 1
      },
      {
        "label": "11:00",
        "timeSec": 660,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "tAwJr6TVv48",
        "title": "The Chinese Meta Has Shifted From \"Makes Sense\" To \"WTF\"",
        "url": "https://www.youtube.com/watch?v=tAwJr6TVv48",
        "channel": "Aussie_Drongo",
        "publishedAt": "2026-07-14T14:00:23+00:00",
        "viewCount": 17652,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Feudal aggression",
          "actions": [
            "Feudal aggression",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Byzantines",
            "Delhi Sultanate",
            "English",
            "French"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [
            {
              "label": "5:41",
              "timeSec": 341,
              "mentions": 1
            },
            {
              "label": "8:29",
              "timeSec": 509,
              "mentions": 1
            },
            {
              "label": "11:00",
              "timeSec": 660,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      }
    ]
  },
  "delhisultanate": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [
      "2TC"
    ],
    "commonResources": [],
    "commonTopics": [
      "Economy",
      "Map control",
      "Counterplay"
    ],
    "commonOpponents": [
      "English",
      "Golden Horde",
      "Macedonian Dynasty"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:43",
        "timeSec": 103,
        "mentions": 1
      },
      {
        "label": "30:32",
        "timeSec": 1832,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "0270EMpZV4o",
        "title": "How to Play Delhi Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=0270EMpZV4o",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-08-02T11:30:04+00:00",
        "viewCount": 6384,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "English",
            "Golden Horde",
            "Macedonian Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:43",
              "timeSec": 103,
              "mentions": 1
            },
            {
              "label": "30:32",
              "timeSec": 1832,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      }
    ]
  },
  "holyromanempire": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [],
    "commonTopics": [
      "Map control",
      "Counterplay"
    ],
    "commonOpponents": [
      "Abbasid Dynasty",
      "Ayyubids",
      "Byzantines",
      "Chinese",
      "Delhi Sultanate",
      "English"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "ixg_3zMxsi0",
        "title": "Tughlaq Dynasty vs HRE: Is This The New Meta?",
        "url": "https://www.youtube.com/watch?v=ixg_3zMxsi0",
        "channel": "7dPlanet",
        "publishedAt": "2026-07-25T17:18:19+00:00",
        "viewCount": 13,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Byzantines",
            "Chinese",
            "Delhi Sultanate",
            "English"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "jeannedarc": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 2,
    "requestedSampleSize": 100,
    "coverageNote": "2 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [
      "gold"
    ],
    "commonTopics": [
      "Economy",
      "Counterplay"
    ],
    "commonOpponents": [
      "Ayyubids"
    ],
    "commonMilitaryMentions": [
      "Spearman"
    ],
    "timingSignals": [],
    "sources": [
      {
        "id": "4CJ408PzABI",
        "title": "Macedonians vs Jeanne d'Arc (IA Hardest) - Progression Tracking #14",
        "url": "https://www.youtube.com/watch?v=4CJ408PzABI",
        "channel": "Amnesiye",
        "publishedAt": "2026-08-03T16:00:31+00:00",
        "viewCount": 15,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "gold"
          ],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Ayyubids"
          ],
          "militaryMentions": [
            "Spearman"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "RtmD5LHGlds",
        "title": "GUÍA para FRANCESES y JUANA de ARCO en 2026 | Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=RtmD5LHGlds",
        "channel": "VortiX",
        "publishedAt": "2026-07-29T18:00:02+00:00",
        "viewCount": 2212,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "malians": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [
      "2TC"
    ],
    "commonResources": [],
    "commonTopics": [
      "Age-up",
      "Opening military",
      "Economy"
    ],
    "commonOpponents": [
      "Ottomans"
    ],
    "commonMilitaryMentions": [
      "Spearman"
    ],
    "timingSignals": [],
    "sources": [
      {
        "id": "W-EatjlDJjU",
        "title": "How I Beat Malians with a 2 TC Ottoman Build | Age of Empires IV",
        "url": "https://www.youtube.com/watch?v=W-EatjlDJjU",
        "channel": "hello Tomi",
        "publishedAt": "2026-07-11T18:08:34+00:00",
        "viewCount": 133,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Ottomans"
          ],
          "militaryMentions": [
            "Spearman"
          ],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "mongols": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 4,
    "requestedSampleSize": 100,
    "coverageNote": "4 matching videos found; requested 100",
    "commonActions": [
      "Defensive"
    ],
    "commonResources": [
      "gold"
    ],
    "commonTopics": [
      "Map control",
      "Counterplay",
      "Economy",
      "Opening military",
      "Age-up"
    ],
    "commonOpponents": [
      "Delhi Sultanate",
      "Golden Horde",
      "Jin Dynasty",
      "Macedonian Dynasty",
      "Order of the Dragon"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [
      {
        "label": "25:16",
        "timeSec": 1516,
        "mentions": 1
      },
      {
        "label": "47:47",
        "timeSec": 2867,
        "mentions": 1
      },
      {
        "label": "89:15",
        "timeSec": 5355,
        "mentions": 1
      },
      {
        "label": "116:48",
        "timeSec": 7008,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "dAJwB1HlIkA",
        "title": "How to win with Mongols in under 20 minutes?",
        "url": "https://www.youtube.com/watch?v=dAJwB1HlIkA",
        "channel": "BeastyqtGaming",
        "publishedAt": "2026-07-21T23:30:26+00:00",
        "viewCount": 2493,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "dbqW6d5PsX4",
        "title": "How to Play Mongols Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=dbqW6d5PsX4",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-19T11:40:08+00:00",
        "viewCount": 9703,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Defensive",
          "actions": [
            "Defensive"
          ],
          "resources": [],
          "topics": [
            "Opening military",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Delhi Sultanate",
            "Golden Horde",
            "Jin Dynasty",
            "Macedonian Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "25:16",
              "timeSec": 1516,
              "mentions": 1
            },
            {
              "label": "47:47",
              "timeSec": 2867,
              "mentions": 1
            },
            {
              "label": "89:15",
              "timeSec": 5355,
              "mentions": 1
            },
            {
              "label": "116:48",
              "timeSec": 7008,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "-kYstQVFEMQ",
        "title": "Guía para jugar TEMPLARIOS en 2026 | TUTORIAL AOE4 📚",
        "url": "https://www.youtube.com/watch?v=-kYstQVFEMQ",
        "channel": "VortiX",
        "publishedAt": "2026-07-17T17:00:26+00:00",
        "viewCount": 3983,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "nfNEctEHcKY",
        "title": "This Strategy Should Be Actually Illegal. AoE4. OOTD vs Mongols",
        "url": "https://www.youtube.com/watch?v=nfNEctEHcKY",
        "channel": "ForTheMax",
        "publishedAt": "2026-07-14T16:00:27+00:00",
        "viewCount": 288,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "gold"
          ],
          "topics": [
            "Age-up",
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Order of the Dragon"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "ottomans": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 3,
    "requestedSampleSize": 100,
    "coverageNote": "3 matching videos found; requested 100",
    "commonActions": [
      "2TC"
    ],
    "commonResources": [],
    "commonTopics": [
      "Age-up",
      "Opening military",
      "Economy"
    ],
    "commonOpponents": [
      "Malians"
    ],
    "commonMilitaryMentions": [
      "Spearman"
    ],
    "timingSignals": [],
    "sources": [
      {
        "id": "OW_EzHQozUs",
        "title": "This is why Ottoman is the best civ in Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=OW_EzHQozUs",
        "channel": "GiveUAnxiety",
        "publishedAt": "2026-07-22T21:34:24+00:00",
        "viewCount": 1038,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "nb5RuXu3x9k",
        "title": "Ottoman Guide for July 2026 Age of Empires 4",
        "url": "https://www.youtube.com/watch?v=nb5RuXu3x9k",
        "channel": "GiveUAnxiety",
        "publishedAt": "2026-07-21T18:50:09+00:00",
        "viewCount": 2880,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "W-EatjlDJjU",
        "title": "How I Beat Malians with a 2 TC Ottoman Build | Age of Empires IV",
        "url": "https://www.youtube.com/watch?v=W-EatjlDJjU",
        "channel": "hello Tomi",
        "publishedAt": "2026-07-11T18:08:34+00:00",
        "viewCount": 133,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Opening military",
            "Economy"
          ],
          "opponentCivs": [
            "Malians"
          ],
          "militaryMentions": [
            "Spearman"
          ],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "rus": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 5,
    "requestedSampleSize": 100,
    "coverageNote": "5 matching videos found; requested 100",
    "commonActions": [
      "2TC",
      "Fast Castle",
      "Feudal aggression",
      "All-in",
      "Knight/Raid"
    ],
    "commonResources": [
      "gold"
    ],
    "commonTopics": [
      "Economy",
      "Counterplay",
      "Age-up"
    ],
    "commonOpponents": [
      "Ayyubids",
      "Holy Roman Empire",
      "Macedonian Dynasty",
      "Japanese",
      "Order of the Dragon",
      "Knights Templar"
    ],
    "commonMilitaryMentions": [
      "Knight",
      "Archer"
    ],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:11",
        "timeSec": 71,
        "mentions": 1
      },
      {
        "label": "29:24",
        "timeSec": 1764,
        "mentions": 1
      },
      {
        "label": "54:37",
        "timeSec": 3277,
        "mentions": 1
      },
      {
        "label": "95:00",
        "timeSec": 5700,
        "mentions": 1
      },
      {
        "label": "79:28",
        "timeSec": 4768,
        "mentions": 1
      },
      {
        "label": "95:56",
        "timeSec": 5756,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "d_FEca71_Xo",
        "title": "How to Play HRE Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=d_FEca71_Xo",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-08-06T11:30:33+00:00",
        "viewCount": 8601,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "Fast Castle",
            "Feudal aggression",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Age-up",
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Ayyubids",
            "Holy Roman Empire",
            "Macedonian Dynasty"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:11",
              "timeSec": 71,
              "mentions": 1
            },
            {
              "label": "29:24",
              "timeSec": 1764,
              "mentions": 1
            },
            {
              "label": "54:37",
              "timeSec": 3277,
              "mentions": 1
            },
            {
              "label": "95:00",
              "timeSec": 5700,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "MjwL5w5ZG6A",
        "title": "How to Play Rus Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=MjwL5w5ZG6A",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-24T11:30:18+00:00",
        "viewCount": 12604,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Ayyubids",
            "Japanese",
            "Order of the Dragon"
          ],
          "militaryMentions": [
            "Archer",
            "Knight"
          ],
          "timings": [
            {
              "label": "79:28",
              "timeSec": 4768,
              "mentions": 1
            },
            {
              "label": "95:56",
              "timeSec": 5756,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "560HYfVvVOc",
        "title": "The Rus Gold Economy is IMPRESSIVE - AoE4",
        "url": "https://www.youtube.com/watch?v=560HYfVvVOc",
        "channel": "Cryptic RTS",
        "publishedAt": "2026-07-20T22:56:25+00:00",
        "viewCount": 1022,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [
            "gold"
          ],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [
            "Knights Templar"
          ],
          "militaryMentions": [
            "Knight"
          ],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "LxnA60G5doM",
        "title": "I Trusted Swaggy's Rus Build... It Actually DELIVERED",
        "url": "https://www.youtube.com/watch?v=LxnA60G5doM",
        "channel": "TarantulaVeia_TV",
        "publishedAt": "2026-07-13T18:04:19+00:00",
        "viewCount": 33,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Knight/Raid",
          "actions": [
            "Knight/Raid"
          ],
          "resources": [],
          "topics": [
            "Economy"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "n74D7yb6WVg",
        "title": "The STRONGEST Rus Build You NEED To Be Doing Right Now",
        "url": "https://www.youtube.com/watch?v=n74D7yb6WVg",
        "channel": "Swaggy Professor",
        "publishedAt": "2026-07-11T11:00:03+00:00",
        "viewCount": 6195,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "sengokudaimyo": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 1,
    "requestedSampleSize": 100,
    "coverageNote": "1 matching videos found; requested 100",
    "commonActions": [],
    "commonResources": [],
    "commonTopics": [],
    "commonOpponents": [],
    "commonMilitaryMentions": [],
    "timingSignals": [],
    "sources": [
      {
        "id": "pHf8TdPhan8",
        "title": "AoE-IV By Numbers: Sengoku Landmarks",
        "url": "https://www.youtube.com/watch?v=pHf8TdPhan8",
        "channel": "RivtalDM",
        "publishedAt": "2026-07-10T00:32:39+00:00",
        "viewCount": 111,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  },
  "tughlaqdynasty": {
    "schemaVersion": 1,
    "windowStart": "2026-07-09",
    "windowEnd": "2026-08-08",
    "sampleSize": 3,
    "requestedSampleSize": 100,
    "coverageNote": "3 matching videos found; requested 100",
    "commonActions": [
      "Defensive",
      "2TC",
      "All-in"
    ],
    "commonResources": [
      "food",
      "gold",
      "wood"
    ],
    "commonTopics": [
      "Map control",
      "Counterplay",
      "Age-up",
      "Opening military",
      "Economy"
    ],
    "commonOpponents": [
      "Abbasid Dynasty",
      "Byzantines",
      "English",
      "Ayyubids",
      "Chinese",
      "Delhi Sultanate"
    ],
    "commonMilitaryMentions": [],
    "timingSignals": [
      {
        "label": "0:00",
        "timeSec": 0,
        "mentions": 1
      },
      {
        "label": "1:48",
        "timeSec": 108,
        "mentions": 1
      },
      {
        "label": "22:45",
        "timeSec": 1365,
        "mentions": 1
      }
    ],
    "sources": [
      {
        "id": "oAXCW0uVLIE",
        "title": "Toxic Tughlaq Playstyle | S13 Tughlaq Guide",
        "url": "https://www.youtube.com/watch?v=oAXCW0uVLIE",
        "channel": "Bexder",
        "publishedAt": "2026-08-02T12:20:04+00:00",
        "viewCount": 95,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "Defensive",
          "actions": [
            "Defensive"
          ],
          "resources": [
            "food",
            "gold",
            "wood"
          ],
          "topics": [
            "Age-up",
            "Opening military",
            "Map control"
          ],
          "opponentCivs": [],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      },
      {
        "id": "UOHPB6LxNq4",
        "title": "How to Play Abbasid Like a Pro - AOE4 Masterclass",
        "url": "https://www.youtube.com/watch?v=UOHPB6LxNq4",
        "channel": "BeastyqtSC2",
        "publishedAt": "2026-07-26T11:30:15+00:00",
        "viewCount": 9311,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": "2TC",
          "actions": [
            "2TC",
            "All-in"
          ],
          "resources": [],
          "topics": [
            "Economy",
            "Counterplay"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Byzantines",
            "English"
          ],
          "militaryMentions": [],
          "timings": [
            {
              "label": "0:00",
              "timeSec": 0,
              "mentions": 1
            },
            {
              "label": "1:48",
              "timeSec": 108,
              "mentions": 1
            },
            {
              "label": "22:45",
              "timeSec": 1365,
              "mentions": 1
            }
          ],
          "confidence": 0.65
        }
      },
      {
        "id": "ixg_3zMxsi0",
        "title": "Tughlaq Dynasty vs HRE: Is This The New Meta?",
        "url": "https://www.youtube.com/watch?v=ixg_3zMxsi0",
        "channel": "7dPlanet",
        "publishedAt": "2026-07-25T17:18:19+00:00",
        "viewCount": 13,
        "transcriptLanguage": null,
        "transcriptSource": "none",
        "transcriptProvider": "none",
        "transcriptStatus": "rate-limited",
        "signals": {
          "archetype": null,
          "actions": [],
          "resources": [],
          "topics": [
            "Map control",
            "Counterplay"
          ],
          "opponentCivs": [
            "Abbasid Dynasty",
            "Ayyubids",
            "Byzantines",
            "Chinese",
            "Delhi Sultanate",
            "English"
          ],
          "militaryMentions": [],
          "timings": [],
          "confidence": 0.65
        }
      }
    ]
  }
} as Record<string, BuildOrderVideoEvidence>
